version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports: 
            - "8010:8010"
        volumes:
            - ./app:/app
            - static_volume:/app/staticfiles
        command: >
         sh -c "python manage.py wait_for_db  &&
                python manage.py collectstatic --no-input --clear &&
                python manage.py migrate &&
                gunicorn finances.wsgi --user user --bind 0.0.0.0:8010 --workers 3" 
        expose:
            - 8010
        env_file:
            - ./.env.prod
        depends_on: 
            - db
    
    db:
        image: postgres:12.3-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/app/staticfiles
        ports:
            - 1337:80
        depends_on:
            - app

volumes:
    postgres_data:
    static_volume:
              