# Generated by Django 3.0.5 on 2020-05-09 02:48

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_annualbudget_expense_expensestag_monthbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('amount', models.FloatField(validators=[core.models.validate_cero], verbose_name='Cantidad')),
                ('periodicity', models.CharField(blank=True, choices=[('m', 'Mensual'), ('a', 'Anual')], max_length=255)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
